language:
- generic
compiler:
- gcc
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
  allow_failures:
  - os: osx
  fast_finish: true
before_script:
- if [ $TRAVIS_OS_NAME == "osx" ]; then brew update -y; else sudo apt-get update -y
  -qq; fi
- if [ $TRAVIS_OS_NAME != "osx" ]; then sudo apt-get install -y -qq build-essential;
  fi
- rm -f main.pdf
script:
- make
- file main.pdf
deploy:
  provider: releases
  api_key:
    secure: s4a+uW4LUoTJelG4VwVShzYtujd5qILsbHzHuLLbTcwd2i6TNfipoQzc+gnAwMV4H6THesmCXEwS7QBFRrRrEzV1LiFtWsb4ONQvOU67Ec+JrAcZj6ZjD+D/jlc6meW4W0ULa8bWI2a8AyzXGy8t116lb33yokE2GSHMFp3GcZZdUSzXyRi/BeNMtG/QZSRMUKGRDyzwoSkfawMLz6J5JY2oqyvSVJZAqNzbpfJGgvkZ1403020He+yL8Ip7UjrSbgL0WSCQD2m6H36kCykyCLYA3OTecdvJHKwV+7Ovhk6yyxz/kdzaTRC+o09OEK+xEDmVjrSHq0uRssZaNQGg/kPU3ilevC3Krg5HhnHhHww1k1/nlvm3zWZZ04hPkLeT16v7j7CNvuJzgN1scNVn9i66kHGxq1V10JQfSV+xG7lq+NzBzay1kSBee8xo6rWx9jiCJmp/8zs4kV1Rmw3e45NlULsyi+PGRErp5R1H6pKAIO8NFngdmRhO7CQu/Dc6gl3DXTUxuMCmdyg9/DQsGO+El6slSu86SE5OiyUCYV9q8r1jTQBizlddjb+LoMi8UQCw0CjwpQuU00fmoyFpAtdh6DXHHHHS3r1ccL0fwFwsoscGV7YKvMZCqL82OHLiXT84JSYryM8fmMoTivRyJGZg4Xdg9i7eAXe4OZGjrOw=
  file: main.pdf
  skip_cleanup: true
  on:
    repo: furushchev/ieee-report-template
    tags: true
